# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
